version: '3'
services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nestdb
    ports:
      - '5432:5432'
