apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
      - name: nestjs
        image: hocvv111999/nestjs-app
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
spec:
  type: NodePort
  selector:
    app: nestjs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
