name: Deploy NestJS to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: hocvv111999
          password: Vuvanhoc286011

      # Build Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: hocvv111999/nestjs-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/nestjs-app nestjs-app=hocvv111999/nestjs-app:latest
          kubectl rollout status deployment/nestjs-app
