name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t hocvv111999/nestjs-app:latest .
        docker push hocvv111999/nestjs-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Kubectl
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > keypair.pem && chmod 600 keypair.pem
        ssh -o StrictHostKeyChecking=no -i keypair.pem ${{ secrets.SSH_HOST }} '
        source ~/.nvm/nvm.sh && node -v
        kubectl set image deployment/nestjs-deployment nestjs=hocvv111999/nestjs-app:latest
